= Vert.x Health Checks

This component provides a simple way to compute health checks.
Health checks are used to express the current state of the application in very simple terms: _UP_ or _DOWN_.

== Using Vert.x Health Checks

Add the following dependency:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-health-check</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-health-check:${maven.version}'
----

=== Creating the health check object.

The central object is {@link io.vertx.ext.healthchecks.HealthChecks}.
You can create a new instance using:

[source,$lang]
----
{@link examples.HealthCheckExamples#example1(io.vertx.core.Vertx)}
----

Once you have created this object you can register and unregister procedures.

== Procedures

A procedure is a function checking some aspect of the system to deduce the current health.
It reports a {@link io.vertx.ext.healthchecks.Status} indicating whether the test has passed or failed.
This function must not block and report to the given {@link io.vertx.core.Promise} whether it succeeded or failed.

When you register a procedure, you give a name and the function (handler) executing the check.

Rules deducing the status are the following:

* if the promise is marked as failed, the check is considered as _KO_
* if the promise is completed successfully but without a {@link io.vertx.ext.healthchecks.Status}, the check is considered as _OK_.
* if the promise is completed successfully with a {@link io.vertx.ext.healthchecks.Status} marked as _OK_, the check is considered as _OK_.
* if the promise is completed successfully with a {@link io.vertx.ext.healthchecks.Status} marked as _KO_, the check is considered as _KO_.

{@link io.vertx.ext.healthchecks.Status} can also provide additional data:

[source,$lang]
----
{@link examples.HealthCheckExamples#example4}
----

Procedures can be organised in groups.
The procedure name indicates the group (separated by `/`).
The procedures are organised as a tree.

[source,$lang]
----
{@link examples.HealthCheckExamples#example3}
----

== Examples of procedures

This section provides example of common health checks.

=== SQL client

This check reports whether a connection to the database can be established:

[source,$lang]
----
{@link examples.HealthCheckExamples#pool}
----

=== Event bus

This check reports whether a consumer is ready on the event bus.
The protocol, in this example, is a simple ping/pong, but it can be more sophisticated.
This check can be used to check whether a verticle is ready if it's listening on a specific event address.

[source,$lang]
----
{@link examples.HealthCheckExamples#eventbus}
----

== Exposing health checks on the event bus

While exposing the health checks using HTTP with the Vert.x web handler is convenient, it can be useful to expose the data differently.
This section gives an example to expose the data on the event bus:

[source,$lang]
----
{@link examples.HealthCheckExamples#publishOnEventBus(io.vertx.core.Vertx, HealthChecks)}
----
